# Site settings
title: Recipes
description: The plain text recipe database
color: "#007FFF"

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  recipes:
    output: true

exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "README.md"]
